version: 2.1

jobs:
  build-and-push:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: default
      - run:
          name: Build Docker Image
          command: docker build -t rasikarajgole/todo-app:$CIRCLE_SHA1 .
      - run:
          name: Push to DockerHub
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker push rasikarajgole/todo-app:$CIRCLE_SHA1

  update-manifest:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Update k8s deployment image tag
          command: |
            git config user.email "$GITHUB_EMAIL"
            git config user.name "CircleCI"
            sed -i "s|image: rasikarajgole/todo-app:.*|image: rasikarajgole/todo-app:$CIRCLE_SHA1|g" k8s/deployment.yml
            git add k8s/deployment.yml
            git commit -m "update image tag to $CIRCLE_SHA1"
            git push https://$GITHUB_TOKEN@github.com/RasikaRajgole/todo-devops-project.git main

workflows:
  deploy:
    jobs:
      - build-and-push:
          filters:
            branches:
              only: main
      - update-manifest:
          requires:
            - build-and-push
          filters:
            branches:
              only: main
