version: 2.1

orbs:
  docker: circleci/docker@2.1.4

jobs:
  test:
    docker:
      - image: cimg/node:18.20
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-deps-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          key: node-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Run tests
          command: npm test -- --watchAll=false --passWithNoTests
      - run:
          name: Build check
          command: npm run build

  build-and-push:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: default
      - run:
          name: Build and Push Docker Image
          command: |
            echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
            docker build -t "$DOCKER_USERNAME/todo-app:$CIRCLE_SHA1" .
            docker tag "$DOCKER_USERNAME/todo-app:$CIRCLE_SHA1" "$DOCKER_USERNAME/todo-app:latest"
            docker push "$DOCKER_USERNAME/todo-app:$CIRCLE_SHA1"
            docker push "$DOCKER_USERNAME/todo-app:latest"

  update-manifest:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Update k8s deployment image tag
          command: |
            git config user.email "$GITHUB_EMAIL"
            git config user.name "CircleCI"
            sed -i "s|image: $DOCKER_USERNAME/todo-app:.*|image: $DOCKER_USERNAME/todo-app:$CIRCLE_SHA1|g" k8s/deployment.yml
            git add k8s/deployment.yml
            git commit -m "ci: update image tag to $CIRCLE_SHA1 [skip ci]"
            git push https://$GITHUB_TOKEN@github.com/RasikaRajgole/todo-devops-project.git main

workflows:
  ci-cd:
    jobs:
      - test:
          filters:
            branches:
              only: main
      - build-and-push:
          requires:
            - test
          filters:
            branches:
              only: main
      - update-manifest:
          requires:
            - build-and-push
          filters:
            branches:
              only: main
